import PushNotification from "react-native-push-notification";

const notfChannelId = "appNotification"

const sendNotification = (appName: String) => {
    createChannelIfNotExists(); //android only

    PushNotification.localNotification({
        /* Android Only Properties */
        channelId: notfChannelId, 
        bigText: `Você está usando o app ${appName} além do limite, porque não fazer uma pausa?`, // (optional) default: "message" prop
        // subText: "This is a subText", // (optional) default: none
        vibrate: true, // (optional) default: true
        priority: "high", // (optional) set notification priority, default: high
        visibility: "public", // (optional) set notification visibility, default: private
        ignoreInForeground: false, // (optional) if true, the notification will not be visible when the app is in the foreground (useful for parity with how iOS notifications appear). should be used in combine with `com.dieam.reactnativepushnotification.notification_foreground` setting
        shortcutId: undefined, // (optional) If this notification is duplicative of a Launcher shortcut, sets the id of the shortcut, in case the Launcher wants to hide the shortcut, default undefined
      
        /* iOS and Android properties */
        id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        title: `Aviso de uso do ${appName}`, // (optional)
        message: `Você está usando o app ${appName} além do limite`, // (required)
        playSound: false, // (optional) default: true
        soundName: "default", // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      });
}

const createChannelIfNotExists = () => {
    PushNotification.channelExists(notfChannelId, function (exists) {
        if(!exists) {
            PushNotification.createChannel(
                {
                channelId: notfChannelId, // (required)
                channelName: "Status", // (required)
                channelDescription: "Notificações sobre usos e atividades", // (optional) default: undefined.
                playSound: false, // (optional) default: true
                soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
                importance: 4, // (optional) default: 4. Int value of the Android notification importance
                vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
                },
                (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
            );
    }
  })
};

export default sendNotification;